language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.0

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Compat; using Compat.Pkg; Pkg.clone(pwd()); Pkg.build("LocalFilters"); Pkg.test("LocalFilters"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Compat; using Compat.Pkg; cd(Pkg.dir("LocalFilters")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  # push coverage results to Codecov
  - julia -e 'using Compat; using Compat.Pkg; cd(Pkg.dir("LocalFilters")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';