name = "LocalFilters"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
uuid = "085fde7c-5f94-55e4-8448-8bbb5db6dde9"
version = "1.2.1"

[deps]

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[targets]
test = ["Test", "Compat"]
