name = "LocalFilters"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>"]
uuid = "085fde7c-5f94-55e4-8448-8bbb5db6dde9"
version = "1.1.0"

[deps]

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
